/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./../src/views/AboutView.vue')['default']
    ComponentBarCharts: typeof import('./../src/materials/charts/Component/ComponentBarCharts.vue')['default']
    ComponentCanvas: typeof import('./../src/editor/canvas/ComponentCanvas.vue')['default']
    ComponentCanvasProperty: typeof import('./../src/editor/panels/property/Component/ComponentCanvasProperty.vue')['default']
    ComponentFormCreate: typeof import('./../src/editor/panels/property/Component/ComponentFormCreate.vue')['default']
    ComponentLayerPanel: typeof import('./../src/editor/panels/layer/ComponentLayerPanel.vue')['default']
    ComponentMaterialItem: typeof import('./../src/editor/panels/meterial/Component/ComponentMaterialItem.vue')['default']
    ComponentMaterialPanel: typeof import('./../src/editor/panels/meterial/ComponentMaterialPanel.vue')['default']
    ComponentMonacoEditor: typeof import('./../src/components/MonacoEditor/ComponentMonacoEditor.vue')['default']
    ComponentNodeProperty: typeof import('./../src/editor/panels/property/Component/ComponentNodeProperty.vue')['default']
    ComponentProperty: typeof import('./../src/editor/panels/property/ComponentProperty.vue')['default']
    ComponentScreenEditor: typeof import('./../src/editor/ComponentScreenEditor.vue')['default']
    ComponentTextMaterial: typeof import('./../src/materials/text/Component/ComponentTextMaterial.vue')['default']
    ComponentToolBarLeft: typeof import('./../src/editor/toolbar/ComponentToolBarLeft.vue')['default']
    ComponentToolBarRight: typeof import('./../src/editor/toolbar/ComponentToolBarRight.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    HomeView: typeof import('./../src/views/HomeView.vue')['default']
    IconCommunity: typeof import('./../src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../src/components/icons/IconEcosystem.vue')['default']
    IconFluentLayer20Filled: typeof import('~icons/fluent/layer20-filled')['default']
    IconFluentMdl2PublishCourse: typeof import('~icons/fluent-mdl2/publish-course')['default']
    IconFluentPanelLeft20Filled: typeof import('~icons/fluent/panel-left20-filled')['default']
    IconFluentPanelRight20Filled: typeof import('~icons/fluent/panel-right20-filled')['default']
    IconFluentPreviewLink20Filled: typeof import('~icons/fluent/preview-link20-filled')['default']
    IconGgExport: typeof import('~icons/gg/export')['default']
    IconLucideImport: typeof import('~icons/lucide/import')['default']
    IconMaterialSymbolsRedo: typeof import('~icons/material-symbols/redo')['default']
    IconMaterialSymbolsUndo: typeof import('~icons/material-symbols/undo')['default']
    IconSiJsonDuotone: typeof import('~icons/si/json-duotone')['default']
    IconSupport: typeof import('./../src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./../src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../src/components/WelcomeItem.vue')['default']
  }
}
